# Generated by Django 4.1.5 on 2023-01-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateTimeField()),
                ('tamaño', models.CharField(max_length=200)),
                ('moldes', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('decoracion', models.TextField()),
                ('cliente', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('vendedor', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
