# Generated by Django 4.1.5 on 2023-01-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
